{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "InvalidDocument",
     "evalue": "cannot encode object: datetime.date(2021, 5, 4), of type: <class 'datetime.date'>",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mInvalidDocument\u001b[0m                           Traceback (most recent call last)",
      "\u001b[1;32md:\\golokaIt\\OMS_Goloka_Server\\practice.ipynb Cell 1\u001b[0m line \u001b[0;36m3\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W0sZmlsZQ%3D%3D?line=23'>24</a>\u001b[0m \u001b[39mfor\u001b[39;00m _ \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(\u001b[39m20\u001b[39m):\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W0sZmlsZQ%3D%3D?line=24'>25</a>\u001b[0m     user_data \u001b[39m=\u001b[39m {\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W0sZmlsZQ%3D%3D?line=25'>26</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39musername\u001b[39m\u001b[39m\"\u001b[39m: fake\u001b[39m.\u001b[39muser_name(),\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W0sZmlsZQ%3D%3D?line=26'>27</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39memail\u001b[39m\u001b[39m\"\u001b[39m: fake\u001b[39m.\u001b[39memail(),\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W0sZmlsZQ%3D%3D?line=36'>37</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mabout\u001b[39m\u001b[39m\"\u001b[39m: fake\u001b[39m.\u001b[39mtext(),\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W0sZmlsZQ%3D%3D?line=37'>38</a>\u001b[0m     }\n\u001b[1;32m---> <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W0sZmlsZQ%3D%3D?line=38'>39</a>\u001b[0m     db\u001b[39m.\u001b[39;49musers\u001b[39m.\u001b[39;49minsert_one(user_data)\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W0sZmlsZQ%3D%3D?line=40'>41</a>\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mDummy data inserted successfully.\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\collection.py:639\u001b[0m, in \u001b[0;36mCollection.insert_one\u001b[1;34m(self, document, bypass_document_validation, session, comment)\u001b[0m\n\u001b[0;32m    635\u001b[0m     document[\u001b[39m\"\u001b[39m\u001b[39m_id\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39m=\u001b[39m ObjectId()  \u001b[39m# type: ignore[index]\u001b[39;00m\n\u001b[0;32m    637\u001b[0m write_concern \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_write_concern_for(session)\n\u001b[0;32m    638\u001b[0m \u001b[39mreturn\u001b[39;00m InsertOneResult(\n\u001b[1;32m--> 639\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_insert_one(\n\u001b[0;32m    640\u001b[0m         document,\n\u001b[0;32m    641\u001b[0m         ordered\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[0;32m    642\u001b[0m         write_concern\u001b[39m=\u001b[39;49mwrite_concern,\n\u001b[0;32m    643\u001b[0m         op_id\u001b[39m=\u001b[39;49m\u001b[39mNone\u001b[39;49;00m,\n\u001b[0;32m    644\u001b[0m         bypass_doc_val\u001b[39m=\u001b[39;49mbypass_document_validation,\n\u001b[0;32m    645\u001b[0m         session\u001b[39m=\u001b[39;49msession,\n\u001b[0;32m    646\u001b[0m         comment\u001b[39m=\u001b[39;49mcomment,\n\u001b[0;32m    647\u001b[0m     ),\n\u001b[0;32m    648\u001b[0m     write_concern\u001b[39m.\u001b[39macknowledged,\n\u001b[0;32m    649\u001b[0m )\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\collection.py:579\u001b[0m, in \u001b[0;36mCollection._insert_one\u001b[1;34m(self, doc, ordered, write_concern, op_id, bypass_doc_val, session, comment)\u001b[0m\n\u001b[0;32m    567\u001b[0m     result \u001b[39m=\u001b[39m sock_info\u001b[39m.\u001b[39mcommand(\n\u001b[0;32m    568\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m__database\u001b[39m.\u001b[39mname,\n\u001b[0;32m    569\u001b[0m         command,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    574\u001b[0m         retryable_write\u001b[39m=\u001b[39mretryable_write,\n\u001b[0;32m    575\u001b[0m     )\n\u001b[0;32m    577\u001b[0m     _check_write_command_response(result)\n\u001b[1;32m--> 579\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__database\u001b[39m.\u001b[39;49mclient\u001b[39m.\u001b[39;49m_retryable_write(acknowledged, _insert_command, session)\n\u001b[0;32m    581\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39misinstance\u001b[39m(doc, RawBSONDocument):\n\u001b[0;32m    582\u001b[0m     \u001b[39mreturn\u001b[39;00m doc\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39m_id\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\mongo_client.py:1493\u001b[0m, in \u001b[0;36mMongoClient._retryable_write\u001b[1;34m(self, retryable, func, session)\u001b[0m\n\u001b[0;32m   1491\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"Internal retryable write helper.\"\"\"\u001b[39;00m\n\u001b[0;32m   1492\u001b[0m \u001b[39mwith\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_tmp_session(session) \u001b[39mas\u001b[39;00m s:\n\u001b[1;32m-> 1493\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_retry_with_session(retryable, func, s, \u001b[39mNone\u001b[39;49;00m)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\mongo_client.py:1360\u001b[0m, in \u001b[0;36mMongoClient._retry_with_session\u001b[1;34m(self, retryable, func, session, bulk)\u001b[0m\n\u001b[0;32m   1350\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"Execute an operation with at most one consecutive retries\u001b[39;00m\n\u001b[0;32m   1351\u001b[0m \n\u001b[0;32m   1352\u001b[0m \u001b[39mReturns func()'s return value on success. On error retries the same\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1355\u001b[0m \u001b[39mRe-raises any exception thrown by func().\u001b[39;00m\n\u001b[0;32m   1356\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m   1357\u001b[0m retryable \u001b[39m=\u001b[39m (\n\u001b[0;32m   1358\u001b[0m     retryable \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39moptions\u001b[39m.\u001b[39mretry_writes \u001b[39mand\u001b[39;00m session \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m session\u001b[39m.\u001b[39min_transaction\n\u001b[0;32m   1359\u001b[0m )\n\u001b[1;32m-> 1360\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_retry_internal(retryable, func, session, bulk)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\_csot.py:106\u001b[0m, in \u001b[0;36mapply.<locals>.csot_wrapper\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    104\u001b[0m         \u001b[39mwith\u001b[39;00m _TimeoutContext(timeout):\n\u001b[0;32m    105\u001b[0m             \u001b[39mreturn\u001b[39;00m func(\u001b[39mself\u001b[39m, \u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m--> 106\u001b[0m \u001b[39mreturn\u001b[39;00m func(\u001b[39mself\u001b[39;49m, \u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\mongo_client.py:1401\u001b[0m, in \u001b[0;36mMongoClient._retry_internal\u001b[1;34m(self, retryable, func, session, bulk)\u001b[0m\n\u001b[0;32m   1399\u001b[0m                 \u001b[39mraise\u001b[39;00m last_error\n\u001b[0;32m   1400\u001b[0m             retryable \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n\u001b[1;32m-> 1401\u001b[0m         \u001b[39mreturn\u001b[39;00m func(session, sock_info, retryable)\n\u001b[0;32m   1402\u001b[0m \u001b[39mexcept\u001b[39;00m ServerSelectionTimeoutError:\n\u001b[0;32m   1403\u001b[0m     \u001b[39mif\u001b[39;00m is_retrying():\n\u001b[0;32m   1404\u001b[0m         \u001b[39m# The application may think the write was never attempted\u001b[39;00m\n\u001b[0;32m   1405\u001b[0m         \u001b[39m# if we raise ServerSelectionTimeoutError on the retry\u001b[39;00m\n\u001b[0;32m   1406\u001b[0m         \u001b[39m# attempt. Raise the original exception instead.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\collection.py:567\u001b[0m, in \u001b[0;36mCollection._insert_one.<locals>._insert_command\u001b[1;34m(session, sock_info, retryable_write)\u001b[0m\n\u001b[0;32m    564\u001b[0m \u001b[39mif\u001b[39;00m bypass_doc_val:\n\u001b[0;32m    565\u001b[0m     command[\u001b[39m\"\u001b[39m\u001b[39mbypassDocumentValidation\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[1;32m--> 567\u001b[0m result \u001b[39m=\u001b[39m sock_info\u001b[39m.\u001b[39;49mcommand(\n\u001b[0;32m    568\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__database\u001b[39m.\u001b[39;49mname,\n\u001b[0;32m    569\u001b[0m     command,\n\u001b[0;32m    570\u001b[0m     write_concern\u001b[39m=\u001b[39;49mwrite_concern,\n\u001b[0;32m    571\u001b[0m     codec_options\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__write_response_codec_options,\n\u001b[0;32m    572\u001b[0m     session\u001b[39m=\u001b[39;49msession,\n\u001b[0;32m    573\u001b[0m     client\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__database\u001b[39m.\u001b[39;49mclient,\n\u001b[0;32m    574\u001b[0m     retryable_write\u001b[39m=\u001b[39;49mretryable_write,\n\u001b[0;32m    575\u001b[0m )\n\u001b[0;32m    577\u001b[0m _check_write_command_response(result)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\helpers.py:279\u001b[0m, in \u001b[0;36m_handle_reauth.<locals>.inner\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    276\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mpymongo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mpool\u001b[39;00m \u001b[39mimport\u001b[39;00m SocketInfo\n\u001b[0;32m    278\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 279\u001b[0m     \u001b[39mreturn\u001b[39;00m func(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[0;32m    280\u001b[0m \u001b[39mexcept\u001b[39;00m OperationFailure \u001b[39mas\u001b[39;00m exc:\n\u001b[0;32m    281\u001b[0m     \u001b[39mif\u001b[39;00m no_reauth:\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\pool.py:907\u001b[0m, in \u001b[0;36mSocketInfo.command\u001b[1;34m(self, dbname, spec, read_preference, codec_options, check, allowable_errors, read_concern, write_concern, parse_write_concern_error, collation, session, client, retryable_write, publish_events, user_fields, exhaust_allowed)\u001b[0m\n\u001b[0;32m    905\u001b[0m \u001b[39m# Catch socket.error, KeyboardInterrupt, etc. and close ourselves.\u001b[39;00m\n\u001b[0;32m    906\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m error:\n\u001b[1;32m--> 907\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_raise_connection_failure(error)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\pool.py:879\u001b[0m, in \u001b[0;36mSocketInfo.command\u001b[1;34m(self, dbname, spec, read_preference, codec_options, check, allowable_errors, read_concern, write_concern, parse_write_concern_error, collation, session, client, retryable_write, publish_events, user_fields, exhaust_allowed)\u001b[0m\n\u001b[0;32m    877\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_raise_if_not_writable(unacknowledged)\n\u001b[0;32m    878\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 879\u001b[0m     \u001b[39mreturn\u001b[39;00m command(\n\u001b[0;32m    880\u001b[0m         \u001b[39mself\u001b[39;49m,\n\u001b[0;32m    881\u001b[0m         dbname,\n\u001b[0;32m    882\u001b[0m         spec,\n\u001b[0;32m    883\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mis_mongos,\n\u001b[0;32m    884\u001b[0m         read_preference,\n\u001b[0;32m    885\u001b[0m         codec_options,\n\u001b[0;32m    886\u001b[0m         session,\n\u001b[0;32m    887\u001b[0m         client,\n\u001b[0;32m    888\u001b[0m         check,\n\u001b[0;32m    889\u001b[0m         allowable_errors,\n\u001b[0;32m    890\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49maddress,\n\u001b[0;32m    891\u001b[0m         listeners,\n\u001b[0;32m    892\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmax_bson_size,\n\u001b[0;32m    893\u001b[0m         read_concern,\n\u001b[0;32m    894\u001b[0m         parse_write_concern_error\u001b[39m=\u001b[39;49mparse_write_concern_error,\n\u001b[0;32m    895\u001b[0m         collation\u001b[39m=\u001b[39;49mcollation,\n\u001b[0;32m    896\u001b[0m         compression_ctx\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mcompression_context,\n\u001b[0;32m    897\u001b[0m         use_op_msg\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mop_msg_enabled,\n\u001b[0;32m    898\u001b[0m         unacknowledged\u001b[39m=\u001b[39;49munacknowledged,\n\u001b[0;32m    899\u001b[0m         user_fields\u001b[39m=\u001b[39;49muser_fields,\n\u001b[0;32m    900\u001b[0m         exhaust_allowed\u001b[39m=\u001b[39;49mexhaust_allowed,\n\u001b[0;32m    901\u001b[0m         write_concern\u001b[39m=\u001b[39;49mwrite_concern,\n\u001b[0;32m    902\u001b[0m     )\n\u001b[0;32m    903\u001b[0m \u001b[39mexcept\u001b[39;00m (OperationFailure, NotPrimaryError):\n\u001b[0;32m    904\u001b[0m     \u001b[39mraise\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\network.py:127\u001b[0m, in \u001b[0;36mcommand\u001b[1;34m(sock_info, dbname, spec, is_mongos, read_preference, codec_options, session, client, check, allowable_errors, address, listeners, max_bson_size, read_concern, parse_write_concern_error, collation, compression_ctx, use_op_msg, unacknowledged, user_fields, exhaust_allowed, write_concern)\u001b[0m\n\u001b[0;32m    125\u001b[0m flags \u001b[39m=\u001b[39m _OpMsg\u001b[39m.\u001b[39mMORE_TO_COME \u001b[39mif\u001b[39;00m unacknowledged \u001b[39melse\u001b[39;00m \u001b[39m0\u001b[39m\n\u001b[0;32m    126\u001b[0m flags \u001b[39m|\u001b[39m\u001b[39m=\u001b[39m _OpMsg\u001b[39m.\u001b[39mEXHAUST_ALLOWED \u001b[39mif\u001b[39;00m exhaust_allowed \u001b[39melse\u001b[39;00m \u001b[39m0\u001b[39m\n\u001b[1;32m--> 127\u001b[0m request_id, msg, size, max_doc_size \u001b[39m=\u001b[39m message\u001b[39m.\u001b[39;49m_op_msg(\n\u001b[0;32m    128\u001b[0m     flags, spec, dbname, read_preference, codec_options, ctx\u001b[39m=\u001b[39;49mcompression_ctx\n\u001b[0;32m    129\u001b[0m )\n\u001b[0;32m    130\u001b[0m \u001b[39m# If this is an unacknowledged write then make sure the encoded doc(s)\u001b[39;00m\n\u001b[0;32m    131\u001b[0m \u001b[39m# are small enough, otherwise rely on the server to return an error.\u001b[39;00m\n\u001b[0;32m    132\u001b[0m \u001b[39mif\u001b[39;00m unacknowledged \u001b[39mand\u001b[39;00m max_bson_size \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m \u001b[39mand\u001b[39;00m max_doc_size \u001b[39m>\u001b[39m max_bson_size:\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\message.py:691\u001b[0m, in \u001b[0;36m_op_msg\u001b[1;34m(flags, command, dbname, read_preference, opts, ctx)\u001b[0m\n\u001b[0;32m    689\u001b[0m     \u001b[39mif\u001b[39;00m ctx:\n\u001b[0;32m    690\u001b[0m         \u001b[39mreturn\u001b[39;00m _op_msg_compressed(flags, command, identifier, docs, opts, ctx)\n\u001b[1;32m--> 691\u001b[0m     \u001b[39mreturn\u001b[39;00m _op_msg_uncompressed(flags, command, identifier, docs, opts)\n\u001b[0;32m    692\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    693\u001b[0m     \u001b[39m# Add the field back to the command.\u001b[39;00m\n\u001b[0;32m    694\u001b[0m     \u001b[39mif\u001b[39;00m identifier:\n",
      "\u001b[1;31mInvalidDocument\u001b[0m: cannot encode object: datetime.date(2021, 5, 4), of type: <class 'datetime.date'>"
     ]
    }
   ],
   "source": [
    "import pymongo\n",
    "from pymongo import MongoClient\n",
    "from faker import Faker\n",
    "import random\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "# Connect to MongoDB\n",
    "mongodb_url = \"mongodb+srv://zaidkhan1682:Oms123456@cluster0.a94nkk2.mongodb.net\"\n",
    "client = MongoClient(mongodb_url)\n",
    "db = client[\"applicants\"]  # Replace \"your_database_name\" with your actual database name\n",
    "\n",
    "# Create a Faker instance\n",
    "fake = Faker()\n",
    "\n",
    "# Define a function to generate random date of birth\n",
    "def generate_dob():\n",
    "    today = datetime.now()\n",
    "    start_date = today - timedelta(days=365 * 30)  # Assuming age between 20 and 30 years\n",
    "    dob = fake.date_of_birth(tzinfo=None, minimum_age=20, maximum_age=30)\n",
    "    # Convert datetime.date to datetime.datetime\n",
    "    return datetime.combine(dob, datetime.min.time())\n",
    "\n",
    "# Insert 20 dummy users\n",
    "for _ in range(20):\n",
    "    user_data = {\n",
    "        \"username\": fake.user_name(),\n",
    "        \"email\": fake.email(),\n",
    "        \"password\": fake.password(),\n",
    "        \"userRole\": random.choice([\"Admin\", \"User\"]),\n",
    "        \"name\": fake.name(),\n",
    "        \"dateOfBirth\": generate_dob(),\n",
    "        \"date\": fake.date_this_decade(),\n",
    "        \"gender\": random.choice([\"Male\", \"Female\", \"Other\"]),\n",
    "        \"resume\": fake.text(),\n",
    "        \"portfolioLink\": fake.url(),\n",
    "        \"contactNo\": fake.phone_number(),\n",
    "        \"about\": fake.text(),\n",
    "    }\n",
    "    db.users.insert_one(user_data)\n",
    "\n",
    "print(\"Dummy data inserted successfully.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "InvalidDocument",
     "evalue": "cannot encode object: datetime.date(2020, 3, 15), of type: <class 'datetime.date'>",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mInvalidDocument\u001b[0m                           Traceback (most recent call last)",
      "\u001b[1;32md:\\golokaIt\\OMS_Goloka_Server\\practice.ipynb Cell 2\u001b[0m line \u001b[0;36m4\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W1sZmlsZQ%3D%3D?line=24'>25</a>\u001b[0m \u001b[39mfor\u001b[39;00m _ \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(\u001b[39m20\u001b[39m):\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W1sZmlsZQ%3D%3D?line=25'>26</a>\u001b[0m     user_data \u001b[39m=\u001b[39m {\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W1sZmlsZQ%3D%3D?line=26'>27</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39musername\u001b[39m\u001b[39m\"\u001b[39m: fake\u001b[39m.\u001b[39muser_name(),\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W1sZmlsZQ%3D%3D?line=27'>28</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39memail\u001b[39m\u001b[39m\"\u001b[39m: fake\u001b[39m.\u001b[39memail(),\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W1sZmlsZQ%3D%3D?line=37'>38</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mabout\u001b[39m\u001b[39m\"\u001b[39m: fake\u001b[39m.\u001b[39mtext(),\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W1sZmlsZQ%3D%3D?line=38'>39</a>\u001b[0m     }\n\u001b[1;32m---> <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W1sZmlsZQ%3D%3D?line=39'>40</a>\u001b[0m     db\u001b[39m.\u001b[39;49musers\u001b[39m.\u001b[39;49minsert_one(user_data)\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/golokaIt/OMS_Goloka_Server/practice.ipynb#W1sZmlsZQ%3D%3D?line=41'>42</a>\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mDummy data inserted successfully.\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\collection.py:639\u001b[0m, in \u001b[0;36mCollection.insert_one\u001b[1;34m(self, document, bypass_document_validation, session, comment)\u001b[0m\n\u001b[0;32m    635\u001b[0m     document[\u001b[39m\"\u001b[39m\u001b[39m_id\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39m=\u001b[39m ObjectId()  \u001b[39m# type: ignore[index]\u001b[39;00m\n\u001b[0;32m    637\u001b[0m write_concern \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_write_concern_for(session)\n\u001b[0;32m    638\u001b[0m \u001b[39mreturn\u001b[39;00m InsertOneResult(\n\u001b[1;32m--> 639\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_insert_one(\n\u001b[0;32m    640\u001b[0m         document,\n\u001b[0;32m    641\u001b[0m         ordered\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[0;32m    642\u001b[0m         write_concern\u001b[39m=\u001b[39;49mwrite_concern,\n\u001b[0;32m    643\u001b[0m         op_id\u001b[39m=\u001b[39;49m\u001b[39mNone\u001b[39;49;00m,\n\u001b[0;32m    644\u001b[0m         bypass_doc_val\u001b[39m=\u001b[39;49mbypass_document_validation,\n\u001b[0;32m    645\u001b[0m         session\u001b[39m=\u001b[39;49msession,\n\u001b[0;32m    646\u001b[0m         comment\u001b[39m=\u001b[39;49mcomment,\n\u001b[0;32m    647\u001b[0m     ),\n\u001b[0;32m    648\u001b[0m     write_concern\u001b[39m.\u001b[39macknowledged,\n\u001b[0;32m    649\u001b[0m )\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\collection.py:579\u001b[0m, in \u001b[0;36mCollection._insert_one\u001b[1;34m(self, doc, ordered, write_concern, op_id, bypass_doc_val, session, comment)\u001b[0m\n\u001b[0;32m    567\u001b[0m     result \u001b[39m=\u001b[39m sock_info\u001b[39m.\u001b[39mcommand(\n\u001b[0;32m    568\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m__database\u001b[39m.\u001b[39mname,\n\u001b[0;32m    569\u001b[0m         command,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    574\u001b[0m         retryable_write\u001b[39m=\u001b[39mretryable_write,\n\u001b[0;32m    575\u001b[0m     )\n\u001b[0;32m    577\u001b[0m     _check_write_command_response(result)\n\u001b[1;32m--> 579\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__database\u001b[39m.\u001b[39;49mclient\u001b[39m.\u001b[39;49m_retryable_write(acknowledged, _insert_command, session)\n\u001b[0;32m    581\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39misinstance\u001b[39m(doc, RawBSONDocument):\n\u001b[0;32m    582\u001b[0m     \u001b[39mreturn\u001b[39;00m doc\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39m_id\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\mongo_client.py:1493\u001b[0m, in \u001b[0;36mMongoClient._retryable_write\u001b[1;34m(self, retryable, func, session)\u001b[0m\n\u001b[0;32m   1491\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"Internal retryable write helper.\"\"\"\u001b[39;00m\n\u001b[0;32m   1492\u001b[0m \u001b[39mwith\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_tmp_session(session) \u001b[39mas\u001b[39;00m s:\n\u001b[1;32m-> 1493\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_retry_with_session(retryable, func, s, \u001b[39mNone\u001b[39;49;00m)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\mongo_client.py:1360\u001b[0m, in \u001b[0;36mMongoClient._retry_with_session\u001b[1;34m(self, retryable, func, session, bulk)\u001b[0m\n\u001b[0;32m   1350\u001b[0m \u001b[39m\u001b[39m\u001b[39m\"\"\"Execute an operation with at most one consecutive retries\u001b[39;00m\n\u001b[0;32m   1351\u001b[0m \n\u001b[0;32m   1352\u001b[0m \u001b[39mReturns func()'s return value on success. On error retries the same\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1355\u001b[0m \u001b[39mRe-raises any exception thrown by func().\u001b[39;00m\n\u001b[0;32m   1356\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m   1357\u001b[0m retryable \u001b[39m=\u001b[39m (\n\u001b[0;32m   1358\u001b[0m     retryable \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39moptions\u001b[39m.\u001b[39mretry_writes \u001b[39mand\u001b[39;00m session \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m session\u001b[39m.\u001b[39min_transaction\n\u001b[0;32m   1359\u001b[0m )\n\u001b[1;32m-> 1360\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_retry_internal(retryable, func, session, bulk)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\_csot.py:106\u001b[0m, in \u001b[0;36mapply.<locals>.csot_wrapper\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    104\u001b[0m         \u001b[39mwith\u001b[39;00m _TimeoutContext(timeout):\n\u001b[0;32m    105\u001b[0m             \u001b[39mreturn\u001b[39;00m func(\u001b[39mself\u001b[39m, \u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m--> 106\u001b[0m \u001b[39mreturn\u001b[39;00m func(\u001b[39mself\u001b[39;49m, \u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\mongo_client.py:1401\u001b[0m, in \u001b[0;36mMongoClient._retry_internal\u001b[1;34m(self, retryable, func, session, bulk)\u001b[0m\n\u001b[0;32m   1399\u001b[0m                 \u001b[39mraise\u001b[39;00m last_error\n\u001b[0;32m   1400\u001b[0m             retryable \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n\u001b[1;32m-> 1401\u001b[0m         \u001b[39mreturn\u001b[39;00m func(session, sock_info, retryable)\n\u001b[0;32m   1402\u001b[0m \u001b[39mexcept\u001b[39;00m ServerSelectionTimeoutError:\n\u001b[0;32m   1403\u001b[0m     \u001b[39mif\u001b[39;00m is_retrying():\n\u001b[0;32m   1404\u001b[0m         \u001b[39m# The application may think the write was never attempted\u001b[39;00m\n\u001b[0;32m   1405\u001b[0m         \u001b[39m# if we raise ServerSelectionTimeoutError on the retry\u001b[39;00m\n\u001b[0;32m   1406\u001b[0m         \u001b[39m# attempt. Raise the original exception instead.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\collection.py:567\u001b[0m, in \u001b[0;36mCollection._insert_one.<locals>._insert_command\u001b[1;34m(session, sock_info, retryable_write)\u001b[0m\n\u001b[0;32m    564\u001b[0m \u001b[39mif\u001b[39;00m bypass_doc_val:\n\u001b[0;32m    565\u001b[0m     command[\u001b[39m\"\u001b[39m\u001b[39mbypassDocumentValidation\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[1;32m--> 567\u001b[0m result \u001b[39m=\u001b[39m sock_info\u001b[39m.\u001b[39;49mcommand(\n\u001b[0;32m    568\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__database\u001b[39m.\u001b[39;49mname,\n\u001b[0;32m    569\u001b[0m     command,\n\u001b[0;32m    570\u001b[0m     write_concern\u001b[39m=\u001b[39;49mwrite_concern,\n\u001b[0;32m    571\u001b[0m     codec_options\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__write_response_codec_options,\n\u001b[0;32m    572\u001b[0m     session\u001b[39m=\u001b[39;49msession,\n\u001b[0;32m    573\u001b[0m     client\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__database\u001b[39m.\u001b[39;49mclient,\n\u001b[0;32m    574\u001b[0m     retryable_write\u001b[39m=\u001b[39;49mretryable_write,\n\u001b[0;32m    575\u001b[0m )\n\u001b[0;32m    577\u001b[0m _check_write_command_response(result)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\helpers.py:279\u001b[0m, in \u001b[0;36m_handle_reauth.<locals>.inner\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    276\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mpymongo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mpool\u001b[39;00m \u001b[39mimport\u001b[39;00m SocketInfo\n\u001b[0;32m    278\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 279\u001b[0m     \u001b[39mreturn\u001b[39;00m func(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[0;32m    280\u001b[0m \u001b[39mexcept\u001b[39;00m OperationFailure \u001b[39mas\u001b[39;00m exc:\n\u001b[0;32m    281\u001b[0m     \u001b[39mif\u001b[39;00m no_reauth:\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\pool.py:907\u001b[0m, in \u001b[0;36mSocketInfo.command\u001b[1;34m(self, dbname, spec, read_preference, codec_options, check, allowable_errors, read_concern, write_concern, parse_write_concern_error, collation, session, client, retryable_write, publish_events, user_fields, exhaust_allowed)\u001b[0m\n\u001b[0;32m    905\u001b[0m \u001b[39m# Catch socket.error, KeyboardInterrupt, etc. and close ourselves.\u001b[39;00m\n\u001b[0;32m    906\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m error:\n\u001b[1;32m--> 907\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_raise_connection_failure(error)\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\pool.py:879\u001b[0m, in \u001b[0;36mSocketInfo.command\u001b[1;34m(self, dbname, spec, read_preference, codec_options, check, allowable_errors, read_concern, write_concern, parse_write_concern_error, collation, session, client, retryable_write, publish_events, user_fields, exhaust_allowed)\u001b[0m\n\u001b[0;32m    877\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_raise_if_not_writable(unacknowledged)\n\u001b[0;32m    878\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 879\u001b[0m     \u001b[39mreturn\u001b[39;00m command(\n\u001b[0;32m    880\u001b[0m         \u001b[39mself\u001b[39;49m,\n\u001b[0;32m    881\u001b[0m         dbname,\n\u001b[0;32m    882\u001b[0m         spec,\n\u001b[0;32m    883\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mis_mongos,\n\u001b[0;32m    884\u001b[0m         read_preference,\n\u001b[0;32m    885\u001b[0m         codec_options,\n\u001b[0;32m    886\u001b[0m         session,\n\u001b[0;32m    887\u001b[0m         client,\n\u001b[0;32m    888\u001b[0m         check,\n\u001b[0;32m    889\u001b[0m         allowable_errors,\n\u001b[0;32m    890\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49maddress,\n\u001b[0;32m    891\u001b[0m         listeners,\n\u001b[0;32m    892\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmax_bson_size,\n\u001b[0;32m    893\u001b[0m         read_concern,\n\u001b[0;32m    894\u001b[0m         parse_write_concern_error\u001b[39m=\u001b[39;49mparse_write_concern_error,\n\u001b[0;32m    895\u001b[0m         collation\u001b[39m=\u001b[39;49mcollation,\n\u001b[0;32m    896\u001b[0m         compression_ctx\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mcompression_context,\n\u001b[0;32m    897\u001b[0m         use_op_msg\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mop_msg_enabled,\n\u001b[0;32m    898\u001b[0m         unacknowledged\u001b[39m=\u001b[39;49munacknowledged,\n\u001b[0;32m    899\u001b[0m         user_fields\u001b[39m=\u001b[39;49muser_fields,\n\u001b[0;32m    900\u001b[0m         exhaust_allowed\u001b[39m=\u001b[39;49mexhaust_allowed,\n\u001b[0;32m    901\u001b[0m         write_concern\u001b[39m=\u001b[39;49mwrite_concern,\n\u001b[0;32m    902\u001b[0m     )\n\u001b[0;32m    903\u001b[0m \u001b[39mexcept\u001b[39;00m (OperationFailure, NotPrimaryError):\n\u001b[0;32m    904\u001b[0m     \u001b[39mraise\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\network.py:127\u001b[0m, in \u001b[0;36mcommand\u001b[1;34m(sock_info, dbname, spec, is_mongos, read_preference, codec_options, session, client, check, allowable_errors, address, listeners, max_bson_size, read_concern, parse_write_concern_error, collation, compression_ctx, use_op_msg, unacknowledged, user_fields, exhaust_allowed, write_concern)\u001b[0m\n\u001b[0;32m    125\u001b[0m flags \u001b[39m=\u001b[39m _OpMsg\u001b[39m.\u001b[39mMORE_TO_COME \u001b[39mif\u001b[39;00m unacknowledged \u001b[39melse\u001b[39;00m \u001b[39m0\u001b[39m\n\u001b[0;32m    126\u001b[0m flags \u001b[39m|\u001b[39m\u001b[39m=\u001b[39m _OpMsg\u001b[39m.\u001b[39mEXHAUST_ALLOWED \u001b[39mif\u001b[39;00m exhaust_allowed \u001b[39melse\u001b[39;00m \u001b[39m0\u001b[39m\n\u001b[1;32m--> 127\u001b[0m request_id, msg, size, max_doc_size \u001b[39m=\u001b[39m message\u001b[39m.\u001b[39;49m_op_msg(\n\u001b[0;32m    128\u001b[0m     flags, spec, dbname, read_preference, codec_options, ctx\u001b[39m=\u001b[39;49mcompression_ctx\n\u001b[0;32m    129\u001b[0m )\n\u001b[0;32m    130\u001b[0m \u001b[39m# If this is an unacknowledged write then make sure the encoded doc(s)\u001b[39;00m\n\u001b[0;32m    131\u001b[0m \u001b[39m# are small enough, otherwise rely on the server to return an error.\u001b[39;00m\n\u001b[0;32m    132\u001b[0m \u001b[39mif\u001b[39;00m unacknowledged \u001b[39mand\u001b[39;00m max_bson_size \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m \u001b[39mand\u001b[39;00m max_doc_size \u001b[39m>\u001b[39m max_bson_size:\n",
      "File \u001b[1;32mc:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymongo\\message.py:691\u001b[0m, in \u001b[0;36m_op_msg\u001b[1;34m(flags, command, dbname, read_preference, opts, ctx)\u001b[0m\n\u001b[0;32m    689\u001b[0m     \u001b[39mif\u001b[39;00m ctx:\n\u001b[0;32m    690\u001b[0m         \u001b[39mreturn\u001b[39;00m _op_msg_compressed(flags, command, identifier, docs, opts, ctx)\n\u001b[1;32m--> 691\u001b[0m     \u001b[39mreturn\u001b[39;00m _op_msg_uncompressed(flags, command, identifier, docs, opts)\n\u001b[0;32m    692\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    693\u001b[0m     \u001b[39m# Add the field back to the command.\u001b[39;00m\n\u001b[0;32m    694\u001b[0m     \u001b[39mif\u001b[39;00m identifier:\n",
      "\u001b[1;31mInvalidDocument\u001b[0m: cannot encode object: datetime.date(2020, 3, 15), of type: <class 'datetime.date'>"
     ]
    }
   ],
   "source": [
    "import pymongo\n",
    "from pymongo import MongoClient\n",
    "from faker import Faker\n",
    "import random\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "# Connect to MongoDB\n",
    "mongodb_url = \"mongodb+srv://zaidkhan1682:Oms123456@cluster0.a94nkk2.mongodb.net\"\n",
    "client = MongoClient(mongodb_url)\n",
    "db = client[\"applicants\"]  # Replace \"your_database_name\" with your actual database name\n",
    "\n",
    "# Create a Faker instance\n",
    "fake = Faker()\n",
    "\n",
    "# Define a function to generate random date of birth\n",
    "def generate_dob():\n",
    "    today = datetime.now()\n",
    "    start_date = today - timedelta(days=365 * 30)  # Assuming age between 20 and 30 years\n",
    "    dob = fake.date_of_birth(tzinfo=None, minimum_age=20, maximum_age=30)\n",
    "    # Ensure the date_of_birth function returns a datetime object\n",
    "    dob_datetime = datetime.combine(dob, datetime.min.time())\n",
    "    return dob_datetime\n",
    "\n",
    "# Insert 20 dummy users\n",
    "for _ in range(20):\n",
    "    user_data = {\n",
    "        \"username\": fake.user_name(),\n",
    "        \"email\": fake.email(),\n",
    "        \"password\": fake.password(),\n",
    "        \"userRole\": random.choice([\"Admin\", \"User\"]),\n",
    "        \"name\": fake.name(),\n",
    "        \"dateOfBirth\": generate_dob(),\n",
    "        \"date\": fake.date_this_decade(),\n",
    "        \"gender\": random.choice([\"Male\", \"Female\", \"Other\"]),\n",
    "        \"resume\": fake.text(),\n",
    "        \"portfolioLink\": fake.url(),\n",
    "        \"contactNo\": fake.phone_number(),\n",
    "        \"about\": fake.text(),\n",
    "    }\n",
    "    db.users.insert_one(user_data)\n",
    "\n",
    "print(\"Dummy data inserted successfully.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dummy data inserted successfully into the applicants collection of the oms database.\n"
     ]
    }
   ],
   "source": [
    "import pymongo\n",
    "from pymongo import MongoClient\n",
    "from faker import Faker\n",
    "import random\n",
    "\n",
    "# Connect to MongoDB\n",
    "mongodb_url = \"mongodb+srv://zaidkhan1682:Oms123456@cluster0.a94nkk2.mongodb.net\"\n",
    "client = MongoClient(mongodb_url)\n",
    "db = client[\"oms\"]  # Use the \"oms\" database\n",
    "collection = db[\"TechTeam\"]  # Use the \"TechTeam\" collection\n",
    "\n",
    "# Create a Faker instance with the 'en_IN' locale for Indian names\n",
    "fake = Faker('en_IN')\n",
    "\n",
    "# Define a function to generate random date of birth, sometimes returning a random string\n",
    "def generate_dob():\n",
    "    # Introduce a random chance (e.g., 10%) to return a random string instead of a datetime object\n",
    "    if random.random() < 0.1:\n",
    "        return fake.word()  # Replace with any random string generation logic\n",
    "\n",
    "    dob = fake.date_of_birth(tzinfo=None, minimum_age=20, maximum_age=30)\n",
    "    # Ensure the date_of_birth function returns a datetime object\n",
    "    dob_datetime = dob.strftime(\"%Y-%m-%d\")\n",
    "    return dob_datetime\n",
    "\n",
    "# Insert 5 dummy applicants with Indian names and Gmail IDs into the TechTeam collection\n",
    "for _ in range(5):\n",
    "    applicant_data = {\n",
    "        \"name\": fake.name(),\n",
    "        \"gender\": random.choice([\"Male\", \"Female\", \"Other\"]),\n",
    "        \"email\": fake.email().split('@')[0] + \"@gmail.com\",\n",
    "        \"Team\": \"TechnicalTeam\",\n",
    "        \"contactNo\": fake.phone_number(),\n",
    "    }\n",
    "    collection.insert_one(applicant_data)\n",
    "\n",
    "print(\"Dummy data inserted successfully into the TechTeam collection of the oms database for the TechnicalTeam.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dummy data inserted successfully into the TechTeam collection of the oms database for the TechnicalTeam.\n"
     ]
    }
   ],
   "source": [
    "import pymongo\n",
    "from pymongo import MongoClient\n",
    "from faker import Faker\n",
    "import random\n",
    "\n",
    "# Connect to MongoDB\n",
    "mongodb_url = \"mongodb+srv://zaidkhan1682:Oms123456@cluster0.a94nkk2.mongodb.net\"\n",
    "client = MongoClient(mongodb_url)\n",
    "db = client[\"test\"]  # Use the \"oms\" database\n",
    "collection = db[\"hrteams\"]  # Use the \"TechTeam\" collection\n",
    "\n",
    "# Create a Faker instance with the 'en_IN' locale for Indian names\n",
    "fake = Faker('en_IN')\n",
    "\n",
    "# Define a function to generate random date of birth, sometimes returning a random string\n",
    "def generate_dob():\n",
    "    # Introduce a random chance (e.g., 10%) to return a random string instead of a datetime object\n",
    "    if random.random() < 0.1:\n",
    "        return fake.word()  # Replace with any random string generation logic\n",
    "\n",
    "    dob = fake.date_of_birth(tzinfo=None, minimum_age=20, maximum_age=30)\n",
    "    # Ensure the date_of_birth function returns a datetime object\n",
    "    dob_datetime = dob.strftime(\"%Y-%m-%d\")\n",
    "    return dob_datetime\n",
    "\n",
    "# Insert 5 dummy applicants with Indian names and Gmail IDs into the TechTeam collection\n",
    "for _ in range(5):\n",
    "    applicant_data = {\n",
    "        \"name\": fake.name(),\n",
    "        \"gender\": random.choice([\"Male\", \"Female\"]),\n",
    "        \"email\": fake.email().split('@')[0] + \"@gmail.com\",\n",
    "        \"Team\": \"HrTeam\",\n",
    "        \"contactNo\": fake.phone_number(),\n",
    "    }\n",
    "    collection.insert_one(applicant_data)\n",
    "\n",
    "print(\"Dummy data inserted successfully into the TechTeam collection of the oms database for the TechnicalTeam.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
